Update buildpack to be based on heroku/nodejs buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -3,83 +3,423 @@
 
 ### Configure environment
 
-set -o errexit  # always exit on error
-set -o pipefail # don't ignore exit codes when piping output
-set -o nounset  # fail on unset variables
-unset GIT_DIR   # Avoid GIT_DIR leak from previous build steps
+set -o errexit    # always exit on error
+set -o pipefail   # don't ignore exit codes when piping output
+unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
+
+### Constants
+
+# This is used by the buildpack stdlib for metrics
+# shellcheck disable=SC2034
+BPLOG_PREFIX="buildpack.nodejs"
+
+### Configure directories
 
 BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
 ENV_DIR=${3:-}
-BUILDPACK_DIR=$(
-  cd "$(dirname "${0:-}")" || exit
-  cd ..
-  pwd
-)
-BIN_DIR="$BUILD_DIR/.heroku/bin"
-DEFAULT_NODE_VERSION=16
+BP_DIR=$(cd "$(dirname "${0:-}")"; cd ..; pwd)
 
-mkdir -p "$BUILD_DIR/.heroku/bin/"
+### Load dependencies
 
-export PATH="$BUILD_DIR/.heroku/node/bin:$BIN_DIR:$PATH"
-echo "-----> BIN_DIR: $BIN_DIR"
-echo "-----> PATH IN BUILD: $PATH"
+# shellcheck source=lib/vendor/stdlib_v7.sh
+source "$BP_DIR/lib/vendor/stdlib_v7.sh"
+# shellcheck source=lib/output.sh
+source "$BP_DIR/lib/output.sh"
+# shellcheck source=lib/monitor.sh
+source "$BP_DIR/lib/monitor.sh"
+# shellcheck source=lib/environment.sh
+source "$BP_DIR/lib/environment.sh"
+# shellcheck source=lib/failure.sh
+source "$BP_DIR/lib/failure.sh"
+# shellcheck source=lib/binaries.sh
+source "$BP_DIR/lib/binaries.sh"
+# shellcheck source=lib/json.sh
+source "$BP_DIR/lib/json.sh"
+# shellcheck source=lib/cache.sh
+source "$BP_DIR/lib/cache.sh"
+# shellcheck source=lib/dependencies.sh
+source "$BP_DIR/lib/dependencies.sh"
+# shellcheck source=lib/plugin.sh
+source "$BP_DIR/lib/plugin.sh"
+# shellcheck source=lib/uuid.sh
+source "$BP_DIR/lib/uuid.sh"
+# shellcheck source=lib/kvstore.sh
+source "$BP_DIR/lib/kvstore.sh"
+# shellcheck source=lib/metadata.sh
+source "$BP_DIR/lib/metadata.sh"
+# shellcheck source=lib/features.sh
+source "$BP_DIR/lib/features.sh"
+# shellcheck source=lib/builddata.sh
+source "$BP_DIR/lib/builddata.sh"
+# shellcheck source=lib/pnpm.sh
+source "$BP_DIR/lib/pnpm.sh"
+# shellcheck source=lib/yarn-2.sh
+source "$BP_DIR/lib/yarn-2.sh"
 
-cd "$BUILD_DIR"
+export PATH="$BUILD_DIR/.heroku/node/bin:$BUILD_DIR/.heroku/yarn/bin":$PATH
 
-### Load Dependencies
-source "$BUILDPACK_DIR/lib/environment.sh"
-source "$BUILDPACK_DIR/lib/json.sh"
-source "$BUILDPACK_DIR/lib/heroku.sh"
+LOG_FILE=$(mktemp -t node-build-log.XXXXX)
+echo "" > "$LOG_FILE"
 
-### Create and export environment variables
+build_start_time=$(nowms)
+
+### Handle errors
+
+handle_failure() {
+  meta_set "node-build-success" "false"
+  header "Build failed"
+  fail_yarn_outdated "$LOG_FILE"
+  fail_yarn_lockfile_outdated "$LOG_FILE"
+  fail_node_install "$LOG_FILE" "$BUILD_DIR"
+  fail_yarn_install "$LOG_FILE" "$BUILD_DIR"
+  fail_invalid_semver "$LOG_FILE"
+  log_other_failures "$LOG_FILE"
+  warn_aws_proxy "$BUILD_DIR"
+  warn_untracked_dependencies "$LOG_FILE"
+  warn_angular_resolution "$LOG_FILE"
+  warn_missing_devdeps "$LOG_FILE" "$BUILD_DIR"
+  warn_econnreset "$LOG_FILE"
+  log_meta_data >> "$BUILDPACK_LOG_FILE"
+  failure_message | output "$LOG_FILE"
+}
+trap 'handle_failure' ERR
+
+### Initalize metadata store
+# Create the metadata store
+meta_init "$CACHE_DIR"
+# Make sure that it's empty and save any previous build's data
+meta_setup
+# the "build-step" key keeps track of where we are in the execution
+# so that we can see where failed builds errored
+meta_set "build-step" "init"
+
+### Check initial state
+
+[ -e "$BUILD_DIR/node_modules" ] && PREBUILD=true || PREBUILD=false
+[ -f "$BUILD_DIR/yarn.lock" ] && YARN=true || YARN=false
+[ -f "$BUILD_DIR/pnpm-lock.yaml" ] && PNPM=true || PNPM=false
+[ -f "$BUILD_DIR/package-lock.json" ] && NPM_LOCK=true || NPM_LOCK=false
+YARN_2=$(detect_yarn_2 "$YARN" "$BUILD_DIR")
+
+### Save build info
+features_init "nodejs" "$BUILD_DIR" "$CACHE_DIR" "$BP_DIR/features"
+log_initial_state
+generate_uuids
+
+### Failures that should be caught immediately
+
+fail_dot_heroku "$BUILD_DIR"
+fail_dot_heroku_node "$BUILD_DIR"
+fail_invalid_package_json "$BUILD_DIR"
+fail_multiple_lockfiles "$BUILD_DIR"
+fail_iojs_unsupported "$BUILD_DIR"
+warn_prebuilt_modules "$BUILD_DIR"
+warn_missing_package_json "$BUILD_DIR"
+
+### Gather more project information
+
+# we know that package.json is valid json, and can pull more data out
+log_project_info "$BUILD_DIR"
+
+### Compile
+
 create_env() {
-  write_profile "$BUILDPACK_DIR" "$BUILD_DIR"
+  write_profile "$BP_DIR" "$BUILD_DIR"
+  write_export "$BP_DIR" "$BUILD_DIR"
   export_env_dir "$ENV_DIR"
+  create_default_env "$YARN"
 }
 
-create_env
+header "Creating runtime environment" | output "$LOG_FILE"
 
-### Install binaries needed for build
-install_binaries() {
-  local node_engine=$(read_json "$BUILD_DIR/package.json" ".engines.node")
-  local npm_engine=$(read_json "$BUILD_DIR/package.json" ".engines.npm")
+mkdir -p "$BUILD_DIR/.heroku/node/"
+cd "$BUILD_DIR"
+create_env # can't pipe the whole thing because piping causes subshells, preventing exports
+list_node_config | output "$LOG_FILE"
+create_build_env
 
-  echo "-----> Install fnm to $BIN_DIR"
+### Configure package manager cache directories
+[ ! "$YARN_CACHE_FOLDER" ] && YARN_CACHE_FOLDER=$(mktemp -d -t yarncache.XXXXX)
+[ ! "$NPM_CONFIG_CACHE" ] && NPM_CONFIG_CACHE=$(mktemp -d -t npmcache.XXXXX)
+export YARN_CACHE_FOLDER NPM_CONFIG_CACHE
 
-  curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "$BIN_DIR" --skip-shell
-  export NODE_OPTIONS=--max_old_space_size=4096
+### Configure vendored package manager
+export VENDOR_PATH
 
-  eval "$(fnm env)"
-
-  if [ -n "$node_engine" ]; then
-    echo "-----> Install nodejs version-d $node_engine from package.json"
-    fnm install "$node_engine"
-  else
-    echo "-----> Install nodejs version-d $DEFAULT_NODE_VERSION"
-    fnm install $DEFAULT_NODE_VERSION
+if [[ "$YARN_2" == "true" ]]; then
+  if [[ "$NODE_MODULES_CACHE" == "true" ]]  && ! node_modules_enabled "$BUILD_DIR"; then
+    warn "
+    The buildpack won't cache the dependencies in .yarn/cache. Since you're using Yarn 2 and Plug'n'Play, you will need to customize your cache or unset NODE_MODULES_CACHE." "https://devcenter.heroku.com/articles/migrating-to-yarn-2#disable-dependency-caching"
   fi
 
-  if [ -n "$npm_engine" ]; then
-    echo "-----> Install npm $npm_engine"
-    npm install -g "$npm_engine"
-  else
-    echo "-----> Use default npm version"
-    npm -v
+  if [[ -f "$BUILD_DIR/.npmrc" ]]; then
+    warn "There is an existing .npmrc file that will not be used. All configurations are read from the .yarnrc.yml file." "https://devcenter.heroku.com/articles/migrating-to-yarn-2"
   fi
 
-  echo "-----> Install pnpm"
-  curl -sL https://unpkg.com/@pnpm/self-installer | node
-  pnpm config set store-dir "$CACHE_DIR"/.pnpm-store
+  if [[ -f "$BUILD_DIR/.yarnrc" ]]; then
+    warn "There is an existing .yarnrc file that will not be used. All configurations are read from the .yarnrc.yml file." "https://devcenter.heroku.com/articles/migrating-to-yarn-2"
+  fi
 
-  echo "-----> Run pnpm install"
-  pnpm install
+  if has_yarn_cache "$BUILD_DIR"; then
+    YARN_CACHE_FOLDER="$BUILD_DIR/.yarn/cache"
+  fi
+
+  ### Configure Yarn 2
+  # fail for no yarnrc.yml
+  fail_missing_yarnrc_yml "$BUILD_DIR"
+
+  # get yarn_path
+  VENDOR_PATH=$(get_yarn_path "$BUILD_DIR")
+
+  # fail for no yarnPath in rc
+  fail_missing_yarn_path "$BUILD_DIR" "$VENDOR_PATH"
+
+  # fail for missing yarn in .yarn/releases
+  fail_missing_yarn_vendor "$BUILD_DIR" "$VENDOR_PATH"
+fi
+
+[[ $(features_get "cache-native-yarn-cache") == "false" ]] && USE_YARN_CACHE=false
+
+if [[ -z "$USE_NPM_INSTALL" ]] && [[ $(features_get_with_blank "use-npm-ci") == "false" ]]; then
+  USE_NPM_INSTALL=true
+fi
+
+install_bins() {
+  local node_engine npm_engine yarn_engine npm_version node_version
+
+  node_engine=$(read_json "$BUILD_DIR/package.json" ".engines.node")
+  npm_engine=$(read_json "$BUILD_DIR/package.json" ".engines.npm")
+  yarn_engine=$(read_json "$BUILD_DIR/package.json" ".engines.yarn")
+
+  if [[ "$YARN_2" == "true" && -n "$yarn_engine" ]]; then
+    warn "You don't need to specify Yarn engine. Heroku will install the latest Yarn 1.x, so that per project version can be used. More information here: https://yarnpkg.com/getting-started/install#global-install"
+    unset yarn_engine
+  fi
+
+  meta_set "node-version-request" "$node_engine"
+  meta_set "npm-version-request" "$npm_engine"
+  meta_set "yarn-version-request" "$yarn_engine"
+
+  echo "engines.node (package.json):  ${node_engine:-unspecified}"
+  echo "engines.npm (package.json):   ${npm_engine:-unspecified (use default)}"
+  if $YARN || [ -n "$yarn_engine" ]; then
+    echo "engines.yarn (package.json):  ${yarn_engine:-unspecified (use default)}"
+  fi
+  echo ""
+
+  warn_node_engine "$node_engine"
+
+  meta_set "build-step" "install-nodejs"
+  monitor "install-node-binary" install_nodejs "$node_engine" "$BUILD_DIR/.heroku/node"
+
+  meta_set "build-step" "install-npm"
+  monitor "install-npm-binary" install_npm "$npm_engine" "$BUILD_DIR/.heroku/node" $NPM_LOCK
+
+  node_version="$(node --version)"
+  mcount "version.node.$node_version"
+  meta_set "node-version" "$node_version"
+
+  if $PNPM; then
+    meta_set "build-step" "install-pnpm"
+    echo "-----> Install pnpm"
+    curl -sL https://unpkg.com/@pnpm/self-installer | node
+    pnpm config set store-dir "$CACHE_DIR"/.pnpm-store
+  fi
+
+  # Download yarn if there is a yarn.lock file or if the user
+  # has specified a version of yarn under "engines". We'll still
+  # only install using yarn if there is a yarn.lock file
+  if $YARN || [ -n "$yarn_engine" ]; then
+    meta_set "build-step" "install-yarn"
+    monitor "install-yarn-binary" install_yarn "$BUILD_DIR/.heroku/yarn" "$yarn_engine"
+  fi
+
+  if $YARN; then
+    mcount "version.yarn.$(yarn --version)"
+    meta_set "yarn-version" "$(yarn --version)"
+  else
+    mcount "version.npm.$(npm --version)"
+    meta_set "npm-version" "$(npm --version)"
+  fi
+
+  warn_old_npm
+
+  if [[ $YARN_2 == true ]]; then
+    YARN=false
+  fi
 }
 
-install_binaries
+header "Installing binaries" | output "$LOG_FILE"
+install_bins | output "$LOG_FILE"
 
-echo "-----> Run prebuild"
-run_prebuild "$BUILD_DIR"
+restore_cache() {
+  local cache_status cache_directories restore_cache_start_time
+  restore_cache_start_time=$(nowms)
 
-echo "-----> Run build"
-run_build "$BUILD_DIR"
+  cache_status="$(get_cache_status "$CACHE_DIR")"
+  cache_directories="$(get_cache_directories "$BUILD_DIR")"
+
+  if $YARN; then
+    if $PREBUILD && [[ "$SKIP_NODE_MODULES_CHECK" == "true" ]]; then
+      echo "Keeping existing node_modules because SKIP_NODE_MODULES_CHECK=${SKIP_NODE_MODULES_CHECK}"
+    elif $PREBUILD; then
+      warn "node_modules checked into source control" "https://devcenter.heroku.com/articles/node-best-practices#only-git-the-important-bits"
+      rm -rf "$BUILD_DIR/node_modules"
+    fi
+  fi
+
+  if [[ "$cache_status" == "disabled" ]]; then
+    header "Restoring cache"
+    echo "Caching has been disabled because NODE_MODULES_CACHE=${NODE_MODULES_CACHE}"
+  elif [[ "$cache_status" == "valid" ]]; then
+    header "Restoring cache"
+    if [[ "$cache_directories" == "" ]]; then
+      restore_default_cache_directories "$BUILD_DIR" "$CACHE_DIR" "$YARN_CACHE_FOLDER"
+    else
+      restore_custom_cache_directories "$BUILD_DIR" "$CACHE_DIR" "$cache_directories"
+    fi
+  elif [[ "$cache_status" == "new-signature" ]]; then
+    header "Restoring cache"
+    if [[ "$cache_directories" == "" ]]; then
+      echo "Cached directories were not restored due to a change in version of node, npm, yarn or stack"
+      echo "Module installation may take longer for this build"
+    else
+      # If the user has specified custom cache directories, be more explicit
+      echo "Invalidating cache due to a change in version of node, npm, yarn or stack"
+      echo "Will not restore the following directories for this build:"
+      for directory in $cache_directories; do
+        echo "  $directory"
+      done
+    fi
+  else
+    # No cache exists, be silent
+    :
+  fi
+
+  mcount "cache.$cache_status"
+  meta_set "cache-status" "$cache_status"
+  meta_time "restore-cache-time" "$restore_cache_start_time"
+}
+
+meta_set "build-step" "restore-cache"
+restore_cache | output "$LOG_FILE"
+
+build_dependencies() {
+  local cache_status start
+
+  cache_status="$(get_cache_status "$CACHE_DIR")"
+  start=$(nowms)
+  if [[ "$YARN_2" == "true" ]]; then
+    yarn_2_install "$BUILD_DIR"
+  elif $YARN; then
+    yarn_node_modules "$BUILD_DIR"
+  elif $PNPM; then
+    pnpm_node_modules "$BUILD_DIR"
+  elif $PREBUILD; then
+    echo "Prebuild detected (node_modules already exists)"
+    npm_rebuild "$BUILD_DIR"
+  else
+    npm_node_modules "$BUILD_DIR"
+  fi
+
+  mtime "modules.time.cache.$cache_status" "${start}"
+
+  meta_set "build-step" "build-script"
+  header "Build"
+  run_build_script "$BUILD_DIR"
+}
+
+meta_set "build-step" "install-dependencies"
+log_build_scripts "$BUILD_DIR"
+run_prebuild_script "$BUILD_DIR" | output "$LOG_FILE"
+header "Installing dependencies" | output "$LOG_FILE"
+build_dependencies | output "$LOG_FILE"
+
+cache_build() {
+  local cache_directories cache_build_start_time
+  cache_build_start_time=$(nowms)
+  cache_directories="$(get_cache_directories "$BUILD_DIR")"
+
+  clear_cache "$CACHE_DIR"
+  if $PNPM; then
+    echo "- pnpm (nothing to cache)"
+  elif ! ${NODE_MODULES_CACHE:-true}; then
+    # we've already warned that caching is disabled in the restore step
+    # so be silent here
+    :
+  elif [[ "$cache_directories" == "" ]]; then
+    header "Caching build"
+    save_default_cache_directories "$BUILD_DIR" "$CACHE_DIR" "$YARN_CACHE_FOLDER"
+  else
+    header "Caching build"
+    save_custom_cache_directories "$BUILD_DIR" "$CACHE_DIR" "$cache_directories"
+  fi
+  save_signature "$CACHE_DIR"
+  meta_time "save-cache-time" "$cache_build_start_time"
+}
+
+prune_devdependencies() {
+  if $YARN || $YARN_2; then
+    yarn_prune_devdependencies "$BUILD_DIR" "$YARN_CACHE_FOLDER"
+  elif $PNPM; then
+    echo "Not pruning when using pnpm"
+  else
+    npm_prune_devdependencies "$BUILD_DIR"
+  fi
+}
+
+if $YARN_2; then
+  meta_set "build-step" "save-cache"
+  cache_build | output "$LOG_FILE"
+  meta_set "build-step" "prune-dependencies"
+  header "Pruning devDependencies" | output "$LOG_FILE"
+  prune_devdependencies | output "$LOG_FILE"
+elif "$YARN" && "$USE_YARN_CACHE" && [[ "$(get_cache_directories "$BUILD_DIR")" == "" ]]; then
+  meta_set "build-step" "prune-dependencies"
+  header "Pruning devDependencies" | output "$LOG_FILE"
+  prune_devdependencies | output "$LOG_FILE"
+  meta_set "build-step" "save-cache"
+  cache_build | output "$LOG_FILE"
+elif $PNPM; then
+  meta_set "build-step" "save-cache"
+  cache_build | output "$LOG_FILE"
+  meta_set "build-step" "prune-dependencies"
+  header "Pruning devDependencies" | output "$LOG_FILE"
+  prune_devdependencies | output "$LOG_FILE"
+else
+  meta_set "build-step" "save-cache"
+  cache_build | output "$LOG_FILE"
+  meta_set "build-step" "prune-dependencies"
+  header "Pruning devDependencies" | output "$LOG_FILE"
+  prune_devdependencies | output "$LOG_FILE"
+fi
+
+meta_set "build-step" "cleanup-script"
+run_cleanup_script "$BUILD_DIR" | output "$LOG_FILE"
+
+summarize_build() {
+  if $NODE_VERBOSE; then
+    list_dependencies "$BUILD_DIR"
+  fi
+
+  mmeasure 'modules.size' "$(measure_size)"
+  meta_set "node-modules-size" "$(measure_size)"
+}
+
+meta_set "build-step" "install-metrics-plugin"
+install_plugin "$BP_DIR" "$BUILD_DIR"
+
+meta_set "build-step" "summarize"
+header "Build succeeded!" | output "$LOG_FILE"
+mcount "compile"
+summarize_build | output "$LOG_FILE"
+meta_set "node-build-success" "true"
+meta_time "build-time" "$build_start_time"
+
+warn_no_start "$BUILD_DIR"
+warn_unmet_dep "$LOG_FILE"
+warn_old_npm_lockfile $NPM_LOCK
+
+meta_set "build-step" "finished"
+log_meta_data >> "$BUILDPACK_LOG_FILE"
